# Generated by Django 4.1.3 on 2023-01-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gallery_images",
            old_name="gallery_img_486_by_165",
            new_name="gallery_img_url",
        ),
    ]
