# Generated by Django 4.1.3 on 2022-12-09 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapters",
            name="chapter_number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="value has to be above 0"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="chapters",
            name="slug_chapter_title",
            field=models.SlugField(max_length=170),
        ),
        migrations.AlterField(
            model_name="comics",
            name="comic_description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="comics", name="slug", field=models.SlugField(max_length=170),
        ),
        migrations.AlterField(
            model_name="gallery_images",
            name="gallery_img_placement_number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="value has to be above 0"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="landing_page_images",
            name="landing_page_img_carousel_placement_number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="value has to be above 0"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="pages",
            name="page_number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="value has to be above 0"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="volumes",
            name="slug_volume_title",
            field=models.SlugField(max_length=170),
        ),
        migrations.AlterField(
            model_name="volumes",
            name="vol_number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="value has to be above 0"
                    )
                ]
            ),
        ),
    ]
