# Generated by Django 4.1.3 on 2023-01-25 13:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0003_alter_personnel_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPages",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("page_name", models.CharField(max_length=25, unique=True)),
            ],
            options={"verbose_name": "Web Page", "verbose_name_plural": "Web Pages",},
        ),
        migrations.CreateModel(
            name="WebPageTextContent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "text_content_ordering",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="value has to be above 0"
                            )
                        ]
                    ),
                ),
                ("text_content", models.CharField(blank=True, max_length=500)),
                (
                    "page_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cc_app.webpages",
                    ),
                ),
            ],
            options={"verbose_name": "Web Page", "verbose_name_plural": "Web Pages",},
        ),
    ]
