# Generated by Django 4.1.3 on 2023-01-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0004_webpages_webpagetextcontent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WebPageTextContent", new_name="Web_Page_Text_Content",
        ),
        migrations.RenameModel(old_name="WebPages", new_name="Web_Pages",),
        migrations.AlterModelOptions(
            name="web_page_text_content",
            options={"verbose_name": "Text Content For WebPages"},
        ),
    ]
