# Generated by Django 4.1.3 on 2023-01-26 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0005_rename_webpagetextcontent_web_page_text_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Featured_Youtube_videos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("video_name", models.CharField(max_length=50)),
                (
                    "video_ordering",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="value has to be above 0"
                            )
                        ]
                    ),
                ),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Featured Youtube video",
                "verbose_name_plural": "Featured Youtube videos",
            },
        ),
        migrations.AlterModelOptions(
            name="web_page_text_content",
            options={
                "verbose_name": "Text Content For WebPages",
                "verbose_name_plural": "Text Content For WebPages",
            },
        ),
    ]
