# Generated by Django 4.1.3 on 2023-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0007_inquiries"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiries",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
