# Generated by Django 4.1.3 on 2023-01-30 11:46

from django.db import migrations, models

import creative_cortex.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0008_inquiries_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="web_pages",
            name="header_img_url",
            field=models.ImageField(
                null=True,
                storage=creative_cortex.storage_backends.PrivateMediaStorage(),
                upload_to="",
            ),
        ),
    ]
