# Generated by Django 4.1.3 on 2023-02-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0010_alter_comic_pages_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comics",
            name="display_comic",
            field=models.BooleanField(default=False),
        ),
    ]
