# Generated by Django 4.1.6 on 2023-02-08 11:34

from django.db import migrations, models

import creative_cortex.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0011_comics_display_comic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "img_url",
                    models.ImageField(
                        storage=creative_cortex.storage_backends.PrivateMediaStorage(),
                        upload_to="",
                    ),
                ),
                ("img_description", models.CharField(max_length=50)),
                ("img_dimensions", models.CharField(max_length=50)),
                ("img_used_on_site", models.BooleanField(default=False)),
            ],
            options={"verbose_name": "Image", "verbose_name_plural": "Images",},
        ),
    ]
