# Generated by Django 4.1.6 on 2023-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0012_images"),
    ]

    operations = [
        migrations.DeleteModel(name="Images",),
        migrations.AddField(
            model_name="volumes",
            name="volume_description",
            field=models.CharField(default="insert volume description", max_length=500),
        ),
    ]
