# Generated by Django 4.1.6 on 2023-02-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0014_rename_comic_img_376_by_376_comics_comic_img_300_by_300"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personnel",
            old_name="person_img_200_by_260",
            new_name="person_img_426_by_284",
        ),
    ]
