# Generated by Django 4.1.6 on 2023-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0015_rename_person_img_200_by_260_personnel_person_img_426_by_284"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiries",
            name="inquiry",
            field=models.CharField(max_length=500),
        ),
    ]
