# Generated by Django 4.1.6 on 2023-02-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cc_app", "0016_alter_inquiries_inquiry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="landing_page_images",
            old_name="landing_page_img_n_by_n",
            new_name="landing_page_img_2000_by_2000",
        ),
        migrations.AddField(
            model_name="landing_page_images",
            name="landing_page_img_position",
            field=models.CharField(
                choices=[
                    ("left top", "left top"),
                    ("left center", "left center"),
                    ("left bottom", "left bottom"),
                    ("right top", "right top"),
                    ("right center", "right center"),
                    ("right bottom", "right bottom"),
                    ("center top", "center top"),
                    ("center center", "center center"),
                    ("center bottom", "center bottom"),
                ],
                default="center center",
                max_length=15,
            ),
        ),
    ]
